In [36]:
import numpy as np

In [40]:
S = np.array([[1,2,3],[2,3,3],[3,3,3]])
print(S.shape)
print(S)

(3, 3)
[[1 2 3]
 [2 3 3]
 [3 3 3]]


In [51]:
P = np.array([S[i,j]+ S[i,j] + 10 for i in range(S.shape[0])] for j in range(S.shape[0]))

In [52]:
print(P)

[[12 14 16]
 [14 16 16]
 [16 16 16]]


In [28]:
A = np.zeros(0)
print(A)

[]


In [53]:
S+S+10

array([[12, 14, 16],
       [14, 16, 16],
       [16, 16, 16]])

In [54]:
P = pow(S,2)

In [55]:
P

array([[1, 4, 9],
       [4, 9, 9],
       [9, 9, 9]])